import type { Metadata, Viewport } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import CommonHeader from './components/ui/CommonHeader';
import Footer from './components/ui/Footer';
import { ShrunkProvider } from './context/shrunkContext';

const pretendard = localFont({
  src: '../public/fonts/pretendard/PretendardVariable.woff2',
  display: 'swap',
  weight: '100 900',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: 'cover',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr" className={pretendard.variable}>
      <head>
        <meta
          name="facebook-domain-verification"
          content="035cyz121yoowvdg0z05r8621ppprm"
        />
      </head>
      <body className={`${pretendard.className} antialiased`}>
        <ShrunkProvider>
          <CommonHeader />
          {children}
          <Footer />
        </ShrunkProvider>
      </body>
    </html>
  );
}
